### ISSUE TITLE
Support for Sitegeist.PaperTiger?

### ISSUE THREAD

**Issue by lorenzulrich** [die-wegmeister/Wegmeister.DatabaseStorage#34]
[Sitegeist.PaperTiger](https://github.com/sitegeist/Sitegeist.PaperTiger) is a both Node- and Fusion Form-based Form Builder, therefore IMO a de-facto successor of `Neos.Form.Builder`.

While its sibling extension [Sitegeist.StoneTablet](https://github.com/sitegeist/Sitegeist.StoneTablet) has some nice ideas (e.g. bundling all uploaded files and the Excel export to an archive), Wegmeister.DatabaseStorage has far more features, e.g. a view of all values in the backend and the possibility to delete data.

Connecting PaperTiger with DatabaseStorage is quite simple, however DatabaseStorage cannot handle file uploads from PaperTiger.

This raises the following questions to @Benjamin-K: 

* Should we add PaperTiger support for DatabaseStorage as far as this is possible without making it a dependency?
* If not: Should we document steps to implement in the readme?

**Comment by lorenzulrich** [comment]
The configuration is easily done - apart from attachment handling which needs adjustments to the PHP code:

`DatabaseStorage.Definition.fusion`:

```
prototype(Sitegeist.PaperTiger:Action.DatabaseStorage.Definition) < prototype(Neos.Fusion:Component) {
    formIdentifier = ${q(node).property('formIdentifier')}

    renderer = Sitegeist.PaperTiger:Action {
        type = '\\Wegmeister\\DatabaseStorage\\FusionForm\\Runtime\\Action\\DatabaseStorageAction'
        options {
            identifier = ${props.formIdentifier}
            formValues = ${data}
        }
    }
}
```

`DatabaseStorage.Preview.fusion`:

```
prototype(Sitegeist.PaperTiger:Action.DatabaseStorage.Preview) < prototype(Neos.Fusion:Component) {
    formIdentifier = ${q(node).property('formIdentifier')}

    renderer = afx`
        <dl class="papertiger-action-email__list">
            <dt>Formularname</dt>
            <dd>{props.formIdentifier}</dd>
        </dl>
    `
}
```

`DatabaseStorage.yaml`:

```
Sitegeist.PaperTiger:Action.DatabaseStorage:
  superTypes:
    'Sitegeist.PaperTiger:Action': true
  ui:
    label: 'Datenbank-Speicher'
    icon: 'icon-database'
  properties:
    formIdentifier:
      type: string
      ui:
        label: 'Formularname'
        showInCreationDialog: true
        inspector:
          group: 'form'
        help:
          message: 'Wird im Modul Datenbank-Speicher verwendet.'
      validation:
        'Neos.Neos/Validation/NotEmptyValidator': []
        'Neos.Neos/Validation/StringLengthValidator':
          maximum: 255
        'Neos.Neos/Validation/RegularExpressionValidator':
          regularExpression: '/^[a-z0-9\-]+$/i'
          validationErrorMessage: 'Der Tabellen-Name darf nur aus Buchstaben, Zahlen und Bindestrich bestehen.'
```

But as you can see, we have `Sitegeist.PaperTiger:Action` as a `superType` here which will fail if PaperTiger isn't installed. Should we create a `Webmeister.DatabaseStorage.PaperTigerAdaptor`?
